# first useful Makefile

CC=gcc

hnm: 0_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 0_main.c -o hnm
	cp hnm test
	touch 0_main.c

hobjdump: 1_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 1_main.c -o hobjdump
	cp hobjdump test
	touch 1_main.c
