# first useful Makefile

CC=gcc

0-hreadelf: 0_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 0_main.c -o 0-hreadelf
	mv 0-hreadelf test

1-hreadelf: 1_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 1_main.c -o 1-hreadelf
	mv 1-hreadelf test

2-hreadelf: 2_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 2_main.c -o 2-hreadelf
	mv 2-hreadelf test

100-hreadelf: 100_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 100_main.c -o 100-hreadelf
	mv 100-hreadelf test
