# first useful Makefile

CC=gcc

0-hreadelf: 0_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 0_main.c -o 0-hreadelf
	cp 0-hreadelf test

1-hreadelf: 0_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 1_main.c -o 1-hreadelf
	cp 1-hreadelf test

2-hreadelf: 0_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 2_main.c -o 2-hreadelf
	cp 2-hreadelf test
